name: Deploy Frontend to Server (Self-hosted PM2)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Triển khai dự án tự động
        shell: cmd
        run: |
          d:
          cd D:\Travel
          git pull origin master
          npm install
          npm run build
          pm2 restart travel || pm2 start ecosystem.config.js